name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_CLIENT_NAME }}:deploy -f Dockerfile .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_LOGIN }}/${{ secrets.DOCKER_CLIENT_NAME }}:deploy
