name: Build and push

on:
  push:
    branches:
      - master

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: login to docker
        run: |
            docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: build image
        run: docker build -t ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_NAME}}:deploy -f Dockerfile .
      - name: push build
        run: docker push ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_NAME}}:deploy

